# Generated by Django 3.2.18 on 2024-08-29 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teams_in_league', to='core.league'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'league')},
        ),
    ]
