# Generated by Django 3.2.18 on 2024-10-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240829_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
