# Generated by Django 3.2.18 on 2024-10-10 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_match_match_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city'),
        ),
    ]
