# Generated by Django 3.2.18 on 2024-10-10 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_extenduser_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.league'),
        ),
        migrations.AlterUniqueTogether(
            name='league',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='league',
            name='city',
        ),
    ]
