# Generated by Django 3.2.18 on 2024-10-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_match_season'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ranking',
            unique_together={('season', 'league', 'team')},
        ),
    ]
