# Generated by Django 3.2.18 on 2024-10-14 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_ranking_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='season',
        ),
        migrations.AlterUniqueTogether(
            name='ranking',
            unique_together={('league', 'team')},
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='season',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
