# Generated by Django 3.2.18 on 2024-10-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20241020_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_team_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
