# Generated by Django 3.2.18 on 2024-10-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_match_match_result'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerstatistics',
            unique_together={('player', 'match')},
        ),
    ]
