# Generated by Django 3.2.18 on 2024-10-28 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20241028_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extenduser',
            name='player',
        ),
        migrations.AddField(
            model_name='extenduser',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players_in_team', to='core.team'),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstatistics',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='captain',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_of_team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
