# Generated by Django 3.2.18 on 2024-10-28 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20241028_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extenduser',
            name='team',
        ),
    ]
