# Generated by Django 3.2.18 on 2024-10-28 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_extenduser_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players_in_team', to='core.team'),
        ),
    ]
