# Generated by Django 3.2.18 on 2024-10-28 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_notification_is_responded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_responded',
        ),
    ]
