# Generated by Django 3.2.18 on 2024-10-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_notification_is_responded'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
