# Generated by Django 3.2.18 on 2024-11-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_notification_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='logo',
        ),
        migrations.AddField(
            model_name='team',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('match_invite', 'Match Invite'), ('message', 'Message'), ('match_result', 'Match Result'), ('join_request', 'Join Request'), ('team_invite', 'Team Invite')], max_length=20),
        ),
    ]
