# Generated by Django 3.2.18 on 2024-11-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20241113_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='image_url',
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='teams/'),
        ),
    ]
