# Generated by Django 3.2.18 on 2024-11-19 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_city_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerTeamStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('mvp', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='extenduser',
            name='assists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='mvp',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='PlayerStatistics',
        ),
        migrations.AddField(
            model_name='playerteamstatistics',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playerteamstatistics',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='core.team'),
        ),
        migrations.AlterUniqueTogether(
            name='playerteamstatistics',
            unique_together={('player', 'team')},
        ),
    ]
