# Generated by Django 3.2.18 on 2024-11-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_playerstatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerteamstatistics',
            name='date_left',
            field=models.DateField(blank=True, null=True),
        ),
    ]
